# .github/workflows/ci.yml
name: Docker Build Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (test only – no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: zec-arena:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Optional: Optional – run the container and hit /health
      - name: Test container starts
        run: |
          docker run --rm -d --name test-container -p 3001:3001 zec-arena:test
          sleep 10
          curl -f http://localhost:3001/health || (docker logs test-container && exit 1)